spring:
  application:
    name: admin-server
  security:
    user:
      name: admin
      password: admin

server:
  address: localhost
  port: 8769

eureka:
  instance:
    metadata-map:
      user.name: admin
      user.password: admin
    easeRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    ip-address: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS