test:
  uri: lb://httpbin

spring:
  jmx:
    enabled: false
  cloud:
    gateway:
      default-filters:
      - PrefixPath=/httpbin
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      routes:
      # =====================================
      - id: websocket_test
        uri: ws://localhost:9000
        predicates:
        - Path=/echo
      # =====================================
      - id: default_path_to_httpbin
        uri: ${test.uri}
        order: 10000
        predicates:
        - Path=/**
    redis:
      host: localhost
      password: pwd
      port: 6378
    cloud:
      default-filter:
        -name: RequestRateLimit
        args:
          key-resolve:
          rate-limiter:



logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoint.web.exposure.include: '*'